/*
 * Autores:
 * Guillermo Montes Martos
 * Manuel Ruiz López
 *
 */

package GUI;

import NapakalakiGame.Monster;
import java.awt.Font;


public class MonsterView extends javax.swing.JPanel {
    
    private Monster monsterModel;
    private static final String prefix = "/Images/Monsters/";
    private static final String suffix = ".jpg";
    private static final int WIDTH = 200;
    private static final int HEIGHT = 331;


    /**
     * Creates new form MonsterView
     */
    public MonsterView() {
        initComponents();
    }
    
    public void setMonster (Monster m) {
        monsterModel = m;
        
        picture.setIcon(new javax.swing.ImageIcon(getClass().getResource(prefix+monsterModel.getName()+suffix)));
        picture.setSize(WIDTH, HEIGHT);
        
        repaint();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        picture = new javax.swing.JLabel();

        setMaximumSize(new java.awt.Dimension(250, 360));
        setMinimumSize(new java.awt.Dimension(250, 360));
        setName(""); // NOI18N
        setPreferredSize(new java.awt.Dimension(250, 360));
        setVerifyInputWhenFocusTarget(false);

        picture.setMaximumSize(new java.awt.Dimension(200, 331));
        picture.setMinimumSize(new java.awt.Dimension(200, 331));
        picture.setPreferredSize(new java.awt.Dimension(200, 331));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(picture, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(26, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(17, Short.MAX_VALUE)
                .addComponent(picture, javax.swing.GroupLayout.PREFERRED_SIZE, 331, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel picture;
    // End of variables declaration//GEN-END:variables
}
