/*
 * Autores:
 * Guillermo Montes Martos
 * Manuel Ruiz López
 *
 */

package GUI;

import NapakalakiGame.Treasure;
import java.awt.FlowLayout;
import javafx.scene.paint.Color;
import static javax.swing.SwingConstants.*;


public class TreasureView extends javax.swing.JPanel {

    private Treasure treasureModel;
    private boolean selected = false;
    private static final String prefix = "/Images/Treasures/";
    private static final String suffix = ".jpg";
    private static final int WIDTH = 112;
    private static final int HEIGHT = 191;
    
    /**
     * Creates new form TreasureView
     */
    public TreasureView() {
        initComponents();
        setBackground(new java.awt.Color(255, 255, 127));
        setOpaque(selected);
    }
    
    public void setTreasure (Treasure t) {
        treasureModel = t;
        
        treasure.setIcon(new javax.swing.ImageIcon(getClass().getResource(prefix+treasureModel.getName()+suffix)));
        treasure.setSize(WIDTH, HEIGHT);
//        treasure.setHorizontalAlignment(CENTER);
//        treasure.setVerticalAlignment(CENTER);
        treasure.setAlignmentX(CENTER_ALIGNMENT);
        treasure.setAlignmentY(CENTER_ALIGNMENT);
        
        
        repaint();
    }
    
    public boolean isSelected() {
        return selected;
    }
    
    public Treasure getTreasure() {
        return treasureModel;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        treasure = new javax.swing.JLabel();

        setMaximumSize(new java.awt.Dimension(136, 215));
        setMinimumSize(new java.awt.Dimension(136, 215));
        setPreferredSize(new java.awt.Dimension(136, 215));
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                formMouseClicked(evt);
            }
        });

        treasure.setMaximumSize(new java.awt.Dimension(112, 191));
        treasure.setMinimumSize(new java.awt.Dimension(112, 191));
        treasure.setPreferredSize(new java.awt.Dimension(112, 191));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(treasure, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(treasure, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void formMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseClicked
        selected = !selected;
        setOpaque(selected);
        repaint();
    }//GEN-LAST:event_formMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel treasure;
    // End of variables declaration//GEN-END:variables
}
